server:
  port: 8065
  name: Ms Usuario

spring:
  application:
    name: ms-usuario
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/user-blood-testing?retryWrites=true&w=majority
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: local-vh
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    path: /user-api-docs.html
  paths-to-match: /**/user/**

eldorado:
  jwt:
    secret: KaPdRgUkXp2s5v8y/B?E(H+MbQeThVmYq3t6w9z$C&F)J@NcRfUjXnZr4u7x!A%D
    expirationMs: 300000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka